#!/bin/bash

: ${REPO_NAME:="$1"}
: ${REPO_PATH:="$PWD/$REPO_NAME"}
: ${BACKUP_DIR:="$HOME/Dropbox"}
: ${BACKUP_FILENAME:="$BACKUP_DIR/$REPO_NAME.git.tar.gz.gpg"}

TMP_DIR=$(mktemp -d -t git-backup.XXXXXX)
trap "rm -rf \"$TMP_DIR\"" EXIT

gpg -d "$BACKUP_FILENAME" | tar -xzf - -C "$TMP_DIR" &&
  git clone -- "$TMP_DIR/$REPO_NAME.git" "$REPO_PATH"
