#!/bin/bash

tmpdir=$(mktemp -d -t writing.XXX)
gpg -d "$HOME/Dropbox/Documents/writing.git.tar.gz.gpg" |
  tar xz -C "$tmpdir"
git clone -- "$tmpdir/writing.git" "$tmpdir/writing"
pushd "$tmpdir/writing"
